name: Node.js CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get and use VAULT_JSON secret
      run: echo "${{ secrets.VAULT_JSON }}" > vault.json
    - run: npm ci
    - run: npm test
